// examples/frontend/vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { trackVueClick, trackVuePageView } from "./events";

onMounted(() => {
  console.log("DOM ready");
  trackVuePageView();
});

function handleClick() {
  trackVueClick();
}
</script>

<template>
  <main style="padding: 40px">
    <h1>Vue Eventra</h1>

    <button @click="handleClick">
      Click me
    </button>
  </main>
</template>

// examples/frontend/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { trackSvelteClick, trackSveltePageView } from "./lib/events";

  onMount(() => {
    trackSveltePageView();
  });

  function handleClick() {
    trackSvelteClick();
  }
</script>

<main>
  <h1>Svelte Eventra</h1>
  <button on:click={handleClick}>
    Click me
  </button>
</main>
