// examples/frontend/vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { trackFeature } from "./tracker";

onMounted(() => {
  console.log("DOM ready");

  trackFeature("vue_page_view");
});

function handleClick() {
  trackFeature("vue_click");
}
</script>

<template>
  <main style="padding: 40px">
    <h1>Vue Eventra</h1>

    <button @click="handleClick">
      Click me
    </button>
  </main>
</template>

// examples/frontend/react/src/App.tsx
import { useEffect } from "react";
import { trackFeature } from "./tracker";

export default function App() {
  useEffect(() => {
    console.log("DOM ready");
    trackFeature("react_page_view");
  }, []);

  const handleClick = () => {
    trackFeature("react_click");
  };

  return (
    <main style={{ padding: 40 }}>
      <h1>React Eventra</h1>

      <button onClick={handleClick}>
        Click me
      </button>
    </main>
  );
}
