// examples/frontend/next/app/page.tsx
"use client";

import { useEffect } from "react";
import { trackFeature } from "../lib/tracker";

export default function Page() {
  useEffect(() => {
    console.log("DOM ready");

    trackFeature("next_page_view");
  }, []);

  return (
    <main style={{ padding: 40 }}>
      <h1>Next Eventra</h1>

      <button
        onClick={() => {
          trackFeature("next_click");
        }}
      >
        Click me
      </button>
    </main>
  );
}

// examples/frontend/vue/src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { trackFeature } from "./tracker";

onMounted(() => {
  console.log("DOM ready");

  trackFeature("vue_page_view");
});

function handleClick() {
  trackFeature("vue_click");
}
</script>

<template>
  <main style="padding: 40px">
    <h1>Vue Eventra</h1>

    <button @click="handleClick">
      Click me
    </button>
  </main>
</template>
